# Generated by Django 3.1.4 on 2021-01-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_category_oragnization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='oragnization',
            new_name='organization',
        ),
    ]
