# Generated by Django 3.1.4 on 2021-01-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20210120_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='caategory',
            new_name='category',
        ),
    ]
